name: Build Updatesite

on:
  push:
    branches: [main]
  release:
    types: [created]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # run nightly at 3:00 am

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Build and Verify
        run: mvn clean verify
      - name: Check formatting
        run: mvn spotless:check
      - name: Publish Nightly Update Site
        if: github.event_name != 'release' && github.ref == 'refs/heads/main' && github.repository_owner == 'abunai-dev'
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.UPDATE_SITE_DEPLOY_KEY }}
          external_repository: abunai-dev/updatesite
          destination_dir: nightly/evaluationscenario-cwa/
          publish_dir: releng/dev.abunai.evaluationscenario.cwa.updatesite/target/repository
          publish_branch: main
      - name: Publish Release Update Site
        if: github.event_name == 'release' && github.repository_owner == 'abunai-dev'
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.UPDATE_SITE_DEPLOY_KEY }}
          external_repository: abunai-dev/updatesite
          destination_dir: release/evaluationscenario-cwa/${{ github.event.release.tag_name }}
          publish_dir: releng/dev.abunai.evaluationscenario.cwa.updatesite/target/repository
          publish_branch: main
          
